version: "3.7"

volumes:
    wordpress:
        name: wordpress
        driver: local
        driver_opts:
            device: ${PROJECT_DIR}/data/wordpress
            o: bind
            type: none
    mariadb:
        name: mariadb
        driver: local
        driver_opts:
            device: ${PROJECT_DIR}/data/mariadb
            o: bind
            type: none

services:
    mariadb:
        build: 
          context: ./requirements/mariadb
          args:
            DB_NAME: ${DB_NAME}
            DB_USER: ${DB_USER}
            DB_USER_PASSWORD: ${DB_USER_PASSWORD}
            DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        environment:
          - DB_NAME=${DB_NAME}
          - DB_USER=${DB_USER}
          - DB_USER_PASSWORD=${DB_USER_PASSWORD}
          - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        restart: always
        container_name: mariadb
        volumes:
          - mariadb:/var/lib/mysql
        networks: 
          - mynetwork

    nginx:
        build: ./requirements/nginx
        container_name: nginx

        ports: 
          - 443:443
        restart: always
        volumes:
          - wordpress:/var/www/wordpress
        depends_on:
          - wordpress
        networks: 
          - mynetwork

    wordpress:
        #image: wordpress
        build: 
          context: ./requirements/wordpress
          args:
            DB_NAME: ${DB_NAME}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_USER_PASSWORD}
            DB_HOST: ${DB_HOST}
        container_name: wordpress
        restart: always
        environment:
          - DB_NAME=${DB_NAME}
          - DB_USER=${DB_USER}
          - DB_PASSWORD=${DB_USER_PASSWORD}
          - DB_HOST=${DB_HOST}
        volumes:
          - wordpress:/var/www/wordpress
        depends_on:
          - mariadb
        networks: 
          - mynetwork

networks:
    mynetwork:
        name: mynetwork